image: docker:20.10

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: satriagitu/go-crud-postgres
  IMAGE_TAG: latest

stages:
  - build
  - push

before_script:
  - echo "Installing Docker Credential Helper"
  - apt-get update && apt-get install -y docker-credential-secretservice
  - echo "Logging in to Docker Hub"
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin


build_image:
  stage: build
  script:
    - echo "Building Docker image"
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$(echo $CI_COMMIT_SHA | cut -c1-7)
    - docker images  # Periksa daftar image yang ada di lokal

push_image:
  stage: push
  script:
    - echo "Pushing Docker image to Docker Hub"
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:$(echo $CI_COMMIT_SHA | cut -c1-7)
  only:
    - main