stages:
  - build
  - push

variables:
  DOCKER_IMAGE: "satriagitu/go-crud-postgres"
  TAG: $CI_COMMIT_REF_NAME

build-docker:
  stage: build
  image: docker:20.10.24
  services:
    - docker:20.10.24-dind
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE:$TAG .
    - docker tag $DOCKER_IMAGE:$TAG $DOCKER_IMAGE:latest
  only:
    - dev
    - staging
    - main

push-docker:
  stage: push
  image: docker:20.10.24
  services:
    - docker:20.10.24-dind
  script:
    - echo "Pushing Docker image to Docker Hub..."
    - echo "Username $DOCKER_USERNAME"
    - echo "Password $DOCKER_PASSWORD"
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_IMAGE:$TAG
    - docker push $DOCKER_IMAGE:latest
  only:
    - dev
    - staging
    - main
