stages:
  - release
  - docker

image: docker:20.10
services:
  - docker:20.10-dind

variables:
  DOCKER_USERNAME: $CI_REGISTRY_USER
  DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD
  DOCKER_IMAGE: "satria.gitu4/go-crud-postgres"

before_script:
  - apk add --no-cache git

release:
  stage: release
  script:
    - git fetch --tags
    - |
      if [[ "$CI_COMMIT_REF_NAME" == "dev" ]]; then
        LAST_TAG=$(git tag -l "v*-dev" | sort -V | tail -n 1)
        VERSION=$(echo $LAST_TAG | sed 's/-dev//')-dev
      elif [[ "$CI_COMMIT_REF_NAME" == "staging" ]]; then
        LAST_TAG=$(git tag -l "v*-beta" | sort -V | tail -n 1)
        VERSION=$(echo $LAST_TAG | sed 's/-beta//')-beta
      elif [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then
        LAST_TAG=$(git tag -l "v*" | sort -V | tail -n 1)
        VERSION=$(echo $LAST_TAG | sed 's/v//')
      fi
      echo "VERSION=$VERSION"

docker:
  stage: docker
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$VERSION .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$VERSION
  only:
    - dev
    - staging
    - main
