apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-crud
  template:
    metadata:
      labels:
        app: go-crud
    spec:
      containers:
        - name: go-crud
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            {{- if .Values.env.fromSecret }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.env.secretName }}"
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.env.secretName }}"
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.env.secretName }}"
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.env.secretName }}"
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.env.secretName }}"
                  key: DB_NAME
            {{- else }}
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT }}
            - name: DB_USER
              value: {{ .Values.env.DB_USER }}
            - name: DB_PASSWORD
              value: {{ .Values.env.DB_PASSWORD }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME }}
            {{- end }}
