apiVersion: v1
kind: Service
metadata:
  name: go-crud-service
spec:
  selector:
    app: go-crud
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: {{ .Values.service.type }}
