name: Release and Docker Publish

on:
  push:
    branches:
      - dev
      - staging
      - main
    tags:
      - 'v*.*.*'      # Production release
      - 'v*.*.*-beta' # Staging release
      - 'v*.*.*-dev'  # Development release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint Commit Messages
        run: |
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

  docker:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Environment Variables
        id: get-env
        run: |
          if [[ "${{ github.ref }}" == refs/heads/dev ]]; then
            VERSION_TAG="v${{ github.event.release.tag_name }}-dev"
            echo "TAG=$VERSION_TAG" >> $GITHUB_ENV
            echo "APP_ENV=development" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/staging ]]; then
            VERSION_TAG="v${{ github.event.release.tag_name }}-staging"
            echo "TAG=$VERSION_TAG" >> $GITHUB_ENV
            echo "APP_ENV=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/main ]]; then
            VERSION_TAG="v${{ github.event.release.tag_name }}-latest"
            echo "TAG=$VERSION_TAG" >> $GITHUB_ENV
            echo "APP_ENV=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/v*.*.*-beta ]]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "APP_ENV=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/v*.*.*-dev ]]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "APP_ENV=development" >> $GITHUB_ENV
          else
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "APP_ENV=production" >> $GITHUB_ENV
          fi

      # Build and Push Docker Image with Semantic Version (from release tag)
      - name: Build and Push Docker Image (Semantic Version)
        run: |
          docker build --build-arg ENV=${{ env.APP_ENV }} -t satriagitu/go-crud-postgres:${{ env.TAG }} .
          docker push satriagitu/go-crud-postgres:${{ env.TAG }}

      # Build and Push Docker Image with 'latest' or branch-specific tag
      - name: Build and Push Docker Image (Latest or Branch Tag)
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          docker build --build-arg ENV=${{ env.APP_ENV }} -t satriagitu/go-crud-postgres:${{ github.ref_name }} .
          docker push satriagitu/go-crud-postgres:${{ github.ref_name }}
